language: objective-c
osx_image: xcode8
script:
    - xcodebuild -project Wrap.xcodeproj -scheme Wrap-iOS clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - xcodebuild -project Wrap.xcodeproj -scheme Wrap-watchOS clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - xcodebuild -project Wrap.xcodeproj -scheme Wrap-OSX clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - xcodebuild -project Wrap.xcodeproj -scheme WrapTests clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
